name: Release youspotube binaries

on:
  release:
    types:
      - created

jobs:
  release_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
      - name: Create executable with pyinstaller
        run: |
          python -m PyInstaller -F --name ysptb_linux --paths ./src ./src/ysptb.py
      - name: Attach executable to release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'dist/ysptb*'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  release_win:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
      - name: Create executable with pyinstaller
        run: |
          python -m PyInstaller -F --name ysptb_win --paths ./src ./src/ysptb.py
      - name: Attach executable to release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'dist/ysptb*'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  release_mac:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
      - name: Create executable with pyinstaller
        run: |
          python -m PyInstaller -F --name ysptb_mac --paths ./src ./src/ysptb.py
      - name: Attach executable to release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'dist/ysptb*'
          repo-token: ${{ secrets.GITHUB_TOKEN }}